### ISSUE TITLE
Conditional logic

### ISSUE THREAD

**Issue by DFWCS** [wolffe/repeater2-for-gravity-forms#3]
Hey, thanks for the plug-in! It’s been very helpful. I noticed it says it supports conditional in the features, but I can’t seem to get it to work. Is there a trick to it? My repeater fields are displaying no matter what.

thanks

**Comment by wolffe** [comment]
Hey, I need to remove that line from the features :) I don't know how to make it work yet. I'm open to contributions, though.

**Comment by DFWCS** [comment]
Ah, thanks for letting me know.  That will be a great feature once you figure it out... it can be really frustrating to work around.  Good luck!

**Comment by wolffe** [comment]
Thanks!
