### ISSUE TITLE
Repeater breaking forms?

### ISSUE THREAD

**Issue by DFWCS** [wolffe/repeater2-for-gravity-forms#4]
I had to roll back to 2.5.5.3 because the latest version of GF has conditional logic issues, and now I am noticing that if I add or edit a repeater into my form, either the entire form will not display or the new field I try to add into the existing repeater will not repeat.  I have no idea why? Any suggestions?

**Comment by DFWCS** [comment]
I deactivated and reactivate the plugin, deleted and recreated the fields, and now it is working.

**Comment by wolffe** [comment]
I am testing it with the latest version of GF and I will release an update soon.
