### ISSUE TITLE
Won't work when there is more than one Gravity form on a page

### ISSUE THREAD

**Issue by skye-va** [wolffe/repeater2-for-gravity-forms#6]
I've tried testing this and when there is more than one Gravity form on a page, the repeater field doesn't work.

Just in case --  I switched themes to Twenty Twenty One, but confirming it was still broken unfortunately.

**Comment by wolffe** [comment]
Thanks for this report. Any PR is welcome.

**Comment by motifsmedia** [comment]
I'm going to try and fix this today. Really grateful for your plugin, and totally running into this same error. I'll submit a PR when I've figured it out. I have a pretty good idea why this is happening.

**Comment by motifsmedia** [comment]
Ok, it's fixed in this PR https://github.com/wolffe/repeater2-for-gravity-forms/pull/9

**Comment by wolffe** [comment]
Thanks @jeslenbucci I have merged it and released a new version - `2.0.4`.
